### PR TITLE
This PR updates some files to generate the documentation locally

### PR DESCRIPTION
**Pull request by juanjqo**
Hi @mmmarinho and @bvadorno,

I would like to update some documentation details about the DQ robotics, e.g. the CoppeliaSim versions, as suggested by @mmmarinho. However, I was not able to run locally the current sphinx project without update first some requirements and the `conf.py` file.  Therefore, this PR adds minimal modifications to run locally.  

I am using Ubuntu ARM64, Python 3.10 (venv).

This is my workflow to generate the documentation locally (I omitted the virtual Python environment configuration):

```shell
git clone https://github.com/dqrobotics/dqrobotics.github.io.git
cd dqrobotics.github.io/docs
pip install -r requirements.txt
make html
```

Best regards, 

Juancho

### CODE REVIEW

**Comment by mmmarinho** [comment]
@juanjqo 

Thanks! I haven't been running this locally but with contributors we will indeed need that.

I'll have to merge this pull request to be sure that it works. 

However, before that, could you add a comment such as
`# For local builds`
for every new/modified command so that we know which ones are for GitHub pages and which aren't?

**Comment by juanjqo** [comment]
@mmmarinho sure! I added the comment you suggested. There are several warnings (e.g., WARNING: Title underline too short, WARNING: mathjax_config/mathjax2_config does not work for the current MathJax version) in the current master branch that are not related to the proposed PR. I plan to address them in different PRs, if you agree.

**Comment by mmmarinho** [comment]
Hi @juanjqo 

Thanks! Could you add that to the requirements file as well? It seems that it is possible
https://stackoverflow.com/questions/9159757/can-i-add-comments-to-a-pip-requirements-file

Kind regards,
Murilo

**Comment by juanjqo** [comment]
> Hi @juanjqo
> 
> Thanks! Could you add that to the requirements file as well? It seems that it is possible https://stackoverflow.com/questions/9159757/can-i-add-comments-to-a-pip-requirements-file
> 
> Kind regards, Murilo

@mmmarinho nice, I didn't know it was possible. (I implemented the modifications in [fc54bb3](https://github.com/dqrobotics/dqrobotics.github.io/pull/5/commits/fc54bb3b26a6241180a1a813b443911b1eac47a7))

**Pull request merged**
